# This is the default format, ref: http://jekyllrb.com/docs/permalinks/
permalink: /:year/:month/:title.html

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]

# Site information
#
site_url: http://joyus.org
site_note: "Unsorted Notes"
author: Matthew Wang
google_analytics_tracking_id: 'UA-1460037-1'
disqus_short_name: joyusorg
tags_path: /tags.html
rss_path: /rss.xml
